// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:ratemybite/Models/DTOs/ProductDto.dart';
import 'package:ratemybite/Models/Ingredient.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(IngredientAdapter());
    registerAdapter(ProductDtoAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(IngredientAdapter());
    registerAdapter(ProductDtoAdapter());
  }
}
